### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by apenney** [indeedeng/java-dogstatsd-client#23]
Any chance you guys can do a new release?  It looks like you may have some fixes in master for something I'm seeing:

tsd[6437]: ERROR (dogstatsd.py:311): Error receiving datagram
           Traceback (most recent call last):
             File "/opt/datadog-agent/agent/dogstatsd.py", line 299, in start
               aggregator_submit(message)
             File "/opt/datadog-agent/agent/aggregator.py", line 604, in submit_packets
               parsed_packets = self.parse_metric_packet(packet)
             File "/opt/datadog-agent/agent/aggregator.py", line 479, in parse_metric_packet
               raise Exception('Metric value must be a number: %s, %s' % (name, raw_value))
           Exception: Metric value must be a number: responses.inbound.nobid.mean, �

I think the Aug 7th commit for NaN would fix this, but we just need a new release out!

**Comment by ovesh** [comment]
I'll publish a new version today.

**Comment by ovesh** [comment]
`2.0.13` released.

**Comment by apenney** [comment]
Thanks!  I only just saw this, I'm a terrible person :)
